amcl:
  ros__parameters:
    use_sim_time: false
    map_topic: /map
    scan_topic: /scan
    odom_frame_id: odom
    base_frame_id: base_link
    global_frame_id: map
    update_min_d: 0.2
    update_min_a: 0.2

global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 1.0
    publish_frequency: 1.0
    resolution: 0.05
    size_x: 10.0
    size_y: 10.0

local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 10.0
    publish_frequency: 10.0
    resolution: 0.05
    size_x: 5.0
    size_y: 5.0
    rolling_window: true

controller_server:
  ros__parameters:
    use_sim_time: false

planner_server:
  ros__parameters:
    use_sim_time: false

bt_navigator:
  ros__parameters:
    use_sim_time: false

recoveries_server:
  ros__parameters:
    use_sim_time: false

waypoint_follower:
  ros__parameters:
    use_sim_time: false

