# Communication settings
scout_mini_driver:
  can_interface: "can0"          
  baudrate: 500000              
  control_mode: "velocity"       

# Robot parameters
robot_params:
  wheel_base: 0.285             
  wheel_track: 0.36              
  wheel_radius: 0.076            

# Control parameters
control_params:
  max_speed: 2.0                 
  max_acceleration: 1.0          
  max_deceleration: 1.0          
  max_angular_speed: 1.5         

# Topic remappings
topics:
  cmd_vel: "/cmd_vel"            
  odometry: "/odom"              
  joint_states: "/joint_states"  

# Sensor integration
sensors:
  imu:
    enable: true                 
    topic: "/imu"                
  battery:
    enable: true                 
    topic: "/battery_state"      

# Logging
logging:
  level: "info"                  
