pointcloud_to_laserscan_node:
  ros__parameters:
    cloud_in: /rslidar_points
    scan_topic: /scan
    angle_min: -3.14
    angle_max: 3.14
    angle_increment: 0.01
    range_min: 0.1
    range_max: 10.0
    transform_tolerance: 0.01
    use_sim_time: false

