slam_toolbox:
  ros__parameters:
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    resolution: 0.05
    publish_period: 5.0
    use_sim_time: false
    transform_publish_period: 0.05
    max_laser_range: 10.0
    minimum_time_interval: 0.0

